### ISSUE TITLE
Relation and interactions betweeen AT_KDF and AT_KDF_FS are not defined.

### ISSUE THREAD

**Issue by emanjon** [emu-wg/eap-aka-pfs#25]
`AT_KDF carries the legacy KDF value for those EAP peers that cannot or do not want to use this extension.
`
Gives the impression that AT_KDF is ignored when AT_KDF_FS is used...

```
When the FS Key Derivation Function field in the AT_KDF_FS attribute
is set to 1 and the Key Derivation Function field in the AT_KDF
attribute is also set to 1, the Master Key (MK) is derived as follows
below.
```

Gives the impression that they are used together...

The Specification is clear on how to derive keys when AT_KDF in {1} and AT_KDF_FS in {1,2} but does not give any descriptions on how other combinations are supposed to work.

**Comment by emanjon** [comment]
I don't know how this is supposed to work but there are several options for how they are used together.

1. AT_KDF is completely ignored when AT_KDF_FS is used.

2. AT_KDF determines how to derive MK, K_aut, K_re
    AT_KDF_FS determines how to derive MK_ECDHE, K_re, MSK, EMSK

3. Like 2. but the PRF used in deriving MK_ECDHE is determined by AT_KDF.

**Comment by emanjon** [comment]
Reasons that this need to be specified is.

- If someone specifies AT_KDF = 2. How would that work with EAP-AKA' FS
- If someone wants to specify a PQC KEM for AT_KDF_FS. Exactly what should they specify.

**Comment by jariarkko** [comment]
Ok this seems like a fair issues. Thanks for spotting this.

**Comment by emanjon** [comment]
I am fine with b.

The PR should make clear that this updates RFC 9048 with this new requirement.

**Comment by jariarkko** [comment]
Ok

**Comment by jariarkko** [comment]
A PR has been proposed: https://github.com/emu-wg/eap-aka-pfs/pull/36

**Comment by jariarkko** [comment]
Solved per the PR so that I can submit the draft (may not be able to work on Monday due to travel).
