### ISSUE TITLE
More alignment between EAP-AKA' FS and 3GPP TS 33.501?

### ISSUE THREAD

**Issue by emanjon** [emu-wg/eap-aka-pfs#27]
In 3GPP TS 33.501 (SUCI) both Curve25519 and secp256r1 are mandatory to support.

In EAP-AKA' FS only X25519 (Curve25519) is mandatory to support and P-256 (secp256r1) is optional.

Should these be aligned? I.e., should P-256 (secp256r1) be mandatory to support also in EAP-AKA' FS?

**Comment by jariarkko** [comment]
I think yes they should be aligned.

**Comment by jariarkko** [comment]
Closing this issue as the update has been done in the draft already.
