### ISSUE TITLE
Unicode in references

### ISSUE THREAD

**Issue by emanjon** [emu-wg/eap-aka-pfs#3]
-07 seems to have been compiled with an old version on xml2rfc not compatible with the use of unicode in RFC references.

`"[RFC9190]  Preu&#258;&#159; Mattsson, J. and M. Sethi"`

This should be fixed by submitting the xml file for -08. The xml file been fixed to be compatible with the latest version of xml2rfc. Some references might need some optimisation

**Comment by jariarkko** [comment]
Yes. (For some reason I have the most recent xml2rfc on the linux box that I'm compiling these on. But for the final one I can try to compile elsewhere... maybe on the web...)
