### ISSUE TITLE
Post-quantum considerations text

### ISSUE THREAD

**Issue by jariarkko** [emu-wg/eap-aka-pfs#30]
Karl:

The PQ considerations are quite generic and does not really say anything about the security properties of this specific protocol (it even mentions constrained IoT).
 
For example, it could instead talk about specifics of this protocol, e.g., Secrecy: the CK'/IK' goes into the derivation of the output keys, so even if a PQ adversary can compute the joint DH-key, then I assume only the FS property gets broken (possibly). The adversary would still not be able to break the  symmetric key parts, so the established key would still be secret, right?
Authentication: By the same argument: if symmetric key crypto would still be safe PQ, then the adversary won't be able to disrupt authentication and do impersonation attacks, I assume.

**Comment by jariarkko** [comment]
I like your angle on PQ. We need exact text though.

**Comment by emanjon** [comment]
This sounds like good changes
