### ISSUE TITLE
Does the draft need to update both 5448 and 9048?

### ISSUE THREAD

**Issue by jariarkko** [emu-wg/eap-aka-pfs#33]
... since 9048 did *not* obsolete 5448

**Comment by emanjon** [comment]
That is is good question. I changed "updates" from RFC 5448 to RFC 9048 as the document do not even mention RFC 5448 except in the Acknowledgments.

Updating increases visability and makes it easier to find the EAP-AKA'-FS document. If it updates 5448 some more mentioning of 5448 would be needed in the introduction

**Comment by jariarkko** [comment]
Closing, fix merged to the document.
