### ISSUE TITLE
Paul's AD review

### ISSUE THREAD

**Issue by emanjon** [emu-wg/eap-aka-pfs#47]
AD Review draft-ietf-emu-aka-pfs-10

Thanks for the clear document and the extensive Security Considerations.
But also, thanks for seeing a real world problem (compromised long term
secrets) and thinking about how to reduce the impact of these observed
attacks. This is great work!

My only substantive comment is about K_encr and K_auth not being
protected by the ECDHE addition. If I understand it correctly, this is
done to ensure backwards compatibility with equipment that does not yet
support these. And that these values are only used for the EAP-AKA'
channel itself, and all other key derivations used for like packet
encryption is done via the MSK and EMSK values, which do have ECDHE
protection. Perhaps it is worth making that a little more clear.

Another consideration which might have been made, but cannot be read from
the document is that there is no "pinning" when seeing ECDHE once, to
then always insist on requiring it in the future. I assume this might not
work with equipment or connection changes happen in the infrastructure.

Nits:

The first use of RECOMMENDED comes before the RFC2119 information on
what it means.

It might be useful to explain EAP-AKA vs EAP-AKA' - wasn't entirely clear to
me this was not a typo at first.

        have gained much scrutiny

I think you receive scrutiny, not gain it?

        They are a high-value target

s/They/These

        panacea

find a phrasing less obscure to describe this ?

Expand first use of UICC ?

        the 3GPP specifications

Turn into a real reference?

        For X25519/Curve25519

Elsewhere, this is referred to as X25519, and Curve25519 is only used
as a name, not the DHE function, which is only referred to as X25519?
Maybe just call it X25519 here?

**Comment by emanjon** [comment]
> My only substantive comment is about K_encr and K_auth not being
> protected by the ECDHE addition. If I understand it correctly, this is
> done to ensure backwards compatibility with equipment that does not yet
> support these. And that these values are only used for the EAP-AKA'
> channel itself, and all other key derivations used for like packet
> encryption is done via the MSK and EMSK values, which do have ECDHE
> protection. Perhaps it is worth making that a little more clear.

This should definitly be motivated and explained. Meiling Cheng had the same comment.

**Comment by emanjon** [comment]
> Another consideration which might have been made, but cannot be read from
> the document is that there is no "pinning" when seeing ECDHE once, to
> then always insist on requiring it in the future. I assume this might not
> work with equipment or connection changes happen in the infrastructure.

Not sure that pinning is even needed when you have protection against bidding down attacks. Pinning also creates a lot of problems. HTTP Public Key Pinning is now considered obsolete as it lead to HPKP Suicide and RansomPKP. Protection against bidding down is discussed quite much. I don't see any need for pinning or to discuss pinning.

**Comment by emanjon** [comment]
All things except pinning and K_encr and K_auth not being
protected by the ECDHE addition has been addressed. Suggestion is to not do anything about pinning.

**Comment by emanjon** [comment]
@jariarkko @knorrman I have tried to fix all comments received during the IETF last call in master. The thing remaining is

> My only substantive comment is about K_encr and K_auth not being
> protected by the ECDHE addition. If I understand it correctly, this is
> done to ensure backwards compatibility with equipment that does not yet
> support these. And that these values are only used for the EAP-AKA'
> channel itself, and all other key derivations used for like packet
> encryption is done via the MSK and EMSK values, which do have ECDHE
> protection. Perhaps it is worth making that a little more clear.

This was not only requested by Paul but also by Meiling Cheng and should be fixed. @jariarkko @knorrman can one of you fix this last part.

**Comment by knorrman** [comment]
@Paul Wouters and @Meiling Cheng:

K_encr and K_aut are used to encrypt and MAC data in the EAP-Req/AKA'-Challenge message, especially the DH g^x ephemeral pub key. At that point the server does not yet have the corresponding g^y from the peer and cannot compute the DH shared secret. So, K_aut is the authentication key for the DH shared secret and all seems OK.

For K_encr though, an implication is that none of the encrypted data sent in the EAP-Req/AKA'-Challenge message will be forward secret. That data may include re-authentication pseudonyms, so an adversary compromising the long-term key would be able to link re-authentication protocol-runs even when pseudonyms are used.

A solution for that could be to introduce a new (optional) message round trip, assigning pseudonyms after the session key is established. Potentially, pseudonyms could  instead be carried in the EAP-Success message, but those are only optionally protected and I cannot immediately see that it works out in all corner cases.
